ant.dir=ant
build.dir=${ant.dir}/build
build.dir.lib=${build.dir}/WEB-INF/lib
build.dir.web.xml=${build.dir}/WEB-INF/web.xml
classes.dir=${build.dir}/WEB-INF/classes
src.dir=./src
package_name=labs
lib.dir=lib
doc.dir=doc

java.dir=${src.dir}/main/java
webapp.dir=${src.dir}/main/webapp
resources.dir=${src.dir}/main/resources


native2ascii.resources=${resources.dir}/native2ascii

test.dir=${src.dir}/test/java
test.classes.dir=${build.dir}/test/classes
test.reports.dir=${build.dir}/test/reports

# SCP
scp.user=s409577
scp.password=UsYo*0636
scp.server=se.ifmo.ru
scp.dir=wildfly/wildfly-33.0.1.Final/standalone/deployments
scp.port=2222

pscp.path=C:/Program Files/PuTTY/pscp.exe

music.file=C:/Users/User/java_workspace/4sem/opi_web.lab3/music.wav

alt.dir=alt_src
replacements.file=C:/Users/User/java_workspace/4sem/opi_web.lab3/src/main/resources/replacements/replacements.properties

vm.args=-Xmx512m -DmyApp.env=dev
compile.version=1.8