ant.dir=ant
build.dir=${ant.dir}/build
build.dir.lib=${build.dir}/WEB-INF/lib
build.dir.web.xml=${build.dir}/WEB-INF/web.xml
classes.dir=${build.dir}/WEB-INF/classes
src.dir=./src
package_name=labs
lib.dir=lib
doc.dir=doc

java.dir=${src.dir}/main/java
webapp.dir=${src.dir}/main/webapp
resources.dir=${src.dir}/main/resources