<?xml version="1.0"?>
<project name="web.lab3" default="build">
    <property file="build.properties"/>

    <!--    mvn dependency:copy-dependencies -DoutputDirectory=lib-->

    <path id="classpath">
        <fileset dir="${lib.dir}" includes="**/*.jar"/>
    </path>


    <target name="compile" depends="clean">
        <mkdir dir="${classes.dir}"/>
        <javac srcdir="${src.dir}" destdir="${classes.dir}" classpathref="classpath" includeAntRuntime="false"/>
    </target>


    <target name="build" depends="compile">
        <copy todir="${build.dir}">
            <fileset dir="${webapp.dir}"/>
        </copy>
        <copy todir="${build.dir.lib}">
            <fileset dir="${lib.dir}"/>
        </copy>
        <copy todir="${classes.dir}">
            <fileset dir="${resources.dir}"/>
        </copy>

        <war destfile="${build.dir}/${ant.project.name}.war" webxml="${build.dir}/WEB-INF/web.xml">
            <fileset dir="${build.dir}">
                <include name="**/*.*"/>
            </fileset>
            <classes dir="${classes.dir}"/>
        </war>
    </target>


    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>

    <target name="xml">
        <xmlvalidate lenient="yes" failonerror="true">
            <fileset dir="${src.dir}" includes="**/*.xml"/>
        </xmlvalidate>
    </target>

    <target name="doc">

        <mkdir dir="${build.dir}/javadoc"/>
        <javadoc sourcepath="${java.dir}" destdir="${build.dir}/javadoc" classpathref="classpath">
            <doctitle>${ant.project.name} API Documentation</doctitle>
            <classpath refid="classpath"/>
        </javadoc>

        <mkdir dir="${build.dir}/checksums"/>
        <checksum todir="${build.dir}/checksums" algorithm="MD5">
            <fileset dir="${build.dir}"/>
        </checksum>
        <checksum todir="${build.dir}/checksums" algorithm="SHA-1">
            <fileset dir="${build.dir}"/>
        </checksum>

        <mkdir dir="${build.dir}/META-INF"/>
        <manifest file="${build.dir}/META-INF/MANIFEST.MF">
            <attribute name="Created-By" value="Apache Ant"/>
            <attribute name="Built-By" value="${user.name}"/>
        </manifest>

        <jar destfile="${build.dir}/${ant.project.name}-doc.jar"
             basedir="${build.dir}/javadoc"
             manifest="${build.dir}/META-INF/MANIFEST.MF"/>

    </target>

</project>